<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">
  <POU Name="AlbertsDataManager" Id="{d8171ebe-c997-0d84-32d9-c05aeaa63c40}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK AlbertsDataManager EXTENDS TcoData.TcoDataExchange
VAR
	//this variable has to called "_data" - PC app will access this variable by its name.
	_data : AlbertsSettings;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>