<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">
  <POU Name="AlbertsContext" Id="{77d39940-ac26-0912-24b5-a04540c6369c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK AlbertsContext EXTENDS TcoCore.TcoContext
VAR
	Machine : AlbertsMachine(THIS^);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Main" Id="{b613b3f3-a147-0c50-1f7d-e0378b0d00f9}">
      <Declaration><![CDATA[(*~
	<docu>
		<summary>
			Main method of the TcoContext. This is the entry point of any control logic that belongs to this context. 
			The call of this method is ensured by calling the <c>InstanceName.Run()</c> method, and it must not be called explicitly.
			This method is abstract, and it must be overridden in derived block.
		</summary>
	</docu>
~*)
METHOD PROTECTED  Main]]></Declaration>
      <Implementation>
        <ST><![CDATA[Machine();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>