name: Publish

on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Fetch unshallow
        run: git fetch --unshallow
      - name: Run a multi-line script
        env:
          NUGET_ORG_PAT: ${{ secrets.TCOOPENNUGETDOTORGPAT   }}
        run: |
          .\pipelines\runbuild.ps1 -properties @{
            "buildConfig" = "Release";
            "updateAssemblyInfo" = $true;
            "publishNugets" = $true;
            "nugetToken" = ($env:NUGET_ORG_PAT);
            "isTestingEnabled" = $true;
            "testingStrength" = 10;
            "packNugets" = $true;
            }
      - name: Upload test results
        uses: actions/upload-artifact@v2 
        if: success() || failure() 
        with:
          name: test-results
          path: ${{ github.workspace }}\**\TestResults\*.xml            